---
title: "STAT325 Project"
output: html_document
---

```{r setup}
library(tidyverse)
library(mosaic) 
library(ggformula)
library(emmeans)

urchin <- read_csv("data_collection.csv") 

urchin <- urchin |> 
  mutate(high_tide = tide_level >= 1) #create new variable for high or low tide
```

# Summary Statistics

```{r summary_stats}
df_stats(count ~ location, data = urchin)
df_stats(count ~ high_tide, data = urchin)
```

```{r graphics}
gf_point(count ~ location, 
         data = urchin, 
         color = ~high_tide,
         xlab = "Tidepool Location", 
         ylab = "Number of Purple Urchins Observed") + 
  labs(color = "High tide?")

gf_point(count ~ high_tide, 
         data = urchin, 
         color = ~location,
         xlab = "High tide", 
         ylab = "Number of Purple Urchins Observed") + 
  labs(color = "Block (location)")
```

# RCBD

```{r rcbd}
urchin_fit <- aov(count ~ high_tide + location, data = urchin) 
anova(urchin_fit)
```

```{r re}
MSE <- 91.22
MSB <- 692.14
b <- 4
t <- 2
num <- (b - 1) * MSB + b * (t - 1) * MSE
den <- (b * t - 1) * MSE
RE <- num/den
RE
```

